<div id="box-blog" class="clearfix">
<h2><?php echo $this->__('Blog') ?></h2>
	 <div id="box-blog-validate-detail">
		<div class="block-content">
			<p>
				<?php echo $this->__('Find more on') ?>
				<a href="http://alegebio.blogspot.com/p/produse-alimentare.html">
					<input type="button" id="button-blog" title="<?php echo $this->__('%s blog','Alege Bio') ?>" class="button"></input>
				</a>
			</p>
		</div>
	</div>
</div>